
left to right direction

hide fields
hide methods
hide circle

class アクション<<定義>> {
}

class リクエスト<<生成されたもの>> {
}

アクション --> リクエスト : 生成 

class コンポーネント<<定義>> {
}

class ユニット<<生成されたもの>> {
}

コンポーネント --> ユニット : 生成 