@startuml
(*) --> "[1]ゲーム開始"
--> "[2]ターンプレイヤーにチャンスを移動"
-->"[3]ステージが空か？"

if "" then
    -->[YES] "[4]パス名簿リセット"
    --> "[5]アクション起こす"
    --> "[6]即時効果か？"
    if "" then
        -->[YES] "[7]効果解決"
        --> "[8]勝敗判定"
        if "" then
            -->[決着] (*)
        else
            -->[それ以外] "[10]誘発チェック"
        endif
    else
        -->[NO] "[9]ステージに追加"
        --> "[10]誘発チェック"
    endif
    --> "[3]ステージが空か？"
else
    -->[NO] "[11]アクションを起こすか？"
    if "" then
        -->[YES] "[4]パス名簿リセット"
    else
        --> [NO] "[12]パス名簿に登録"
        --> "[13]パス名簿の件数=プレイヤー数か？"
        if "" then
            -->[YES] ”[14]ステージから取出し”
            --> "[7]効果解決"
        else
            --> [NO] "[15]チャンス移動"
            --> "[3]ステージが空か？"
        endif
    endif
endif
@enduml
