@startuml
(*) --> "①ゲーム開始"
--> "②ターンプレイヤーにチャンスを移動"
-->"③ステージが空か？"

if "" then
    -->[YES] "④パス名簿リセット"
    --> "⑤アクション起こす"
    --> "⑥即時効果か？"
    if "" then
        -->[YES] "⑦効果解決"
        --> "⑧勝敗判定"
        --> "⑩誘発チェック"
    else
        -->[NO] "⑨ステージに追加"
        --> "⑩誘発チェック"
    endif
    --> "③ステージが空か？"
else
    -->[NO] "⑪アクションを起こすか？"
    if "" then
        -->[YES] "④パス名簿リセット"
    else
        --> [NO] "⑫パス名簿に登録"
        --> "⑬パス名簿の件数=プレイヤー数か？"
        if "" then
            -->[YES] ”⑭ステージから取出し”
            --> "⑦効果解決"
        else
            --> [NO] "⑮チャンス移動"
            --> "③ステージが空か？"
        endif
    endif
endif
@enduml