@startuml
start
:[1]ゲーム開始;
:[2]ターンプレイヤーにチャンスを移動;
repeat
if ([3]アクションを起こすか？) then (Yes)
    :[4]パス記録のリセット;
    :[5]アクションを起こす;
    :[6]誘発チェック;
    if ([7]即時効果か？) then (Yes)
        :[8]アクションの解決;
        if ([9]勝敗判定) then (決着)
            stop
        endif
    else (No)
        :[10]ステージに追加;
    endif
    :[6]誘発チェック;
else (No)
    :[11]パス記録に登録;
    if ([12]全員がパスしたか？) then (Yes)
        if ([13]ステージにアクションが存在するか？) then (Yes)
            :[14]ステージから取出し;
            :[8]アクションの解決;
            if ([9]勝敗判定) then (決着)
                stop
            endif
            :[6]誘発チェック;
            :[2]ターンプレイヤーにチャンスを移動;
        else (No)
        endif
    else (No)
        :[15]チャンス移動;
    endif
endif
repeat while()
@enduml