@startuml
(*) --> "[10-1]誘発したアクションをプレイヤー毎に誘発リストにまとめる"
--> "誘発リスト全体の件数判定"

if "" then
    -->[1件以上] "[10-2]ターンプレイヤーからターンが回る順に\nプレイヤー毎に誘発リストの即時効果のアクションを解決。"
    -->"[10-3]誘発リストから即時効果のアクションを1つ取り出す"
    -->"[10-4]即時効果のアクションを解決"
    -->"[10-5]勝敗判定"
    -->"[10-6]誘発したアクションをプレイヤー毎の誘発リストに追加"
    -->"[10-7]未解決の即時効果があれば繰り返す"
    if "" then
        -->[YES] "[10-4]即時効果のアクションを解決"
    else
        -->[YES] "[10-2]誘発リストに即時効果のアクションがある\nプレイヤーがいれば繰り返す"
        if "" then
            -->[YES] "[10-2]ターンプレイヤーからターンが回る順に\nプレイヤー毎に誘発リストの即時効果のアクションを解決。"
        else
            -->"[10-8]プレイヤー毎に通常効果のアクションをステージに追加"
            -->"[10-9]通常効果のアクションを任意の順でステージに追加"
            -->"[10-10]未処理のプレイヤーがいれば繰り返す"
            if "" then
                -->[YES] "[10-8]プレイヤー毎に通常効果のアクションをステージに追加"
            else
                -->(*)
            endif
        endif
    endif

else
    -->[NO] (*)
endif

@enduml
