@startuml
'==============================
'【通常効果：アクション毎に処理】
'==============================
start
while ([6-10-1] バッファから該当の通常効果アクションがあるか？) is (Yes)
  :[6-10-2] バッファから通常効果アクションを取り出す;
  if ([6-10-3] 取り出した通常効果のタイミングがメインか判定) then (Yes)
    if ([6-10-4] ステージが空か判定？) then (Yes)
      :[6-10-5] 通常効果アクション\nをステージに追加;
    else (No)
      :[6-10-6] 通常効果アクションを破棄;
    endif
  else (No)
    :[6-10-7] タイミングがクイックの場合、\n通常効果アクションをステージに追加;
  endif
  if ([6-10-8] アクションが誘発したかを判定) then (Yes)
    :[6-10-9] 誘発したアクションをバッファに追加;
    note left
      誘発したアクションのコントローラーは
      起因となったアクションのコントローラー
      になります。
    end note
  else (No)
  endif
endwhile (No)
stop
@enduml
