@startuml
'==============================
'【通常：アクション毎に処理】
'==============================

start
while ([6-10-1] バッファから該当の通常はあるか？) is (Yes)
  :[6-10-2] バッファからリクエストを取り出す;
  if ([6-10-3] 取り出したリクエストのタイミングがメインか判定) then (Yes)
    if ([6-10-4] ステージが空か判定) then (Yes)
      :[6-10-5] リクエストをステージに追加;
    else (No)
      :[6-10-6] リクエストを破棄;
    endif
  else (No)
    :[6-10-7] リクエストをステージに追加;
  endif
  if ([6-10-8] リクエストが新たな誘発を発生させたか？) then (Yes)
    :[6-10-9] 誘発したリクエストをバッファに追加;
    note left
      誘発したリクエストのコントローラーは
      起因となったアクションのコントローラー
      になります。
    end note
  else (No)
  endif
endwhile (No)
stop
@enduml
