@startuml
start
:[10-1]誘発したアクションをプレイヤー毎に誘発リストにまとめる;
while([10-2]誘発リスト全体の件数判定) is (1件以上)
    group 即時効果:プレイヤー単位に繰返し
    note
        順番はターンプレイヤーから
        ターンが回る順に行う
    end note
    repeat :[10-3]プレイヤー毎に誘発リスト\nの即時効果のアクションを解決;
        group 即時効果:アクション単位に繰返し
        repeat :[10-4]誘発リストから即時効果の\nアクションを1つ取り出す;
            :[10-5]即時効果のアクションを解決;
            :[10-6]勝敗判定;
            :[10-7]誘発したアクションを\nプレイヤー毎の誘発リストに追加;
        repeat while ([10-8]未解決の即時効果があれば繰り返す) is (YES)
        end group
    repeat while([10-9]誘発リストに即時効果のアクションがあれば繰り返す) is (YES)
    end group

    group 通常効果
    note
        順番はターンプレイヤーから
        ターンが回る順に行う
    end note
    repeat :[10-10]プレイヤー毎に通常効果\nのアクションをステージに追加;
        :[10-11]通常効果のアクションを\n任意の順でステージに追加;
        :[10-12]誘発したアクションを\nプレイヤー毎の誘発リストに追加;
    repeat while ([10-13]誘発リストに通常効果のアクションがあれば繰り返す) is (YES)
    end group

endwhile (0件)
    stop
@enduml
