@startuml
(*) --> "⑩-1.誘発チェック"

if "" then
    -->[YES] "⑩-2.即時誘発有無判定"
    if "" then
        -->[YES] "⑩-3.効果解決&勝敗判定"
        --> "⑩-4.誘発有無判定"
    else
        -->[NO] "⑩-4.誘発有無判定"
    endif

    if "" then
        -->[YES] "⑩-5.ステージに追加"
        --> "⑩-1.誘発チェック"
    else
        -->[NO] "⑩-1.誘発チェック"
    endif

else
    -->[NO] (*)
endif

@enduml