@startuml
'==============================
'【即時：アクション毎に処理】
'==============================

start
while ([6-5-1] バッファから該当の即時はあるか？) is (Yes)
  :[6-5-2] バッファからリクエストを取り出す;
  :[6-5-3] 取り出したリクエストを解決する;
  if ([6-5-4] 勝敗判定) then (決着)
    stop
  endif
  if ([6-5-5] リクエストが新たな誘発を発生させたか？) then (Yes)
    :[6-5-6] 誘発したリクエストをバッファに追加;
    note left
      誘発したリクエストのコントローラーは
      起因となったアクションのオーナー
      になります。
    end note
  endif
endwhile (No)
stop
@enduml
