@startuml action-resolve-flow
title リクエストの解決

start
:ステージの一番上にあるリクエストを特定する;
if (リクエストの対象が正しいか？) then (Yes)
    :リクエストされたアクションの効果を
    可能な限り実行する;
else (No)
    :効果を発揮せず解決とする;
endif
:リクエストをステージから取り除く;
:キーカードを墓地に移す;
note right
    以下の場合は墓地に移さない
    ・効果でキーカードを場などに出した場合
    ・効果でキーカードを手札に戻した場合
    ・キーユニット条件の場合
end note
stop

@enduml
