@startuml
start
:ライフの一番上のカードを表向きにして
防壁として場に出す;

:ライフの次のカードを表向きにして
兵士として場に出す;

while (兵士と定義されていないキャラクターか？) is (Yes)
    :そのカードを **表向きのまま墓地** に置く;
    if (ライフがなくなったか？) then (Yes)
        :そのプレイヤーは **敗北** する;
        stop
    else (No)
    endif
    :ライフの一番上からカードを1枚取り
    表向きにして **兵士として場に出す** ;
endwhile (No)
stop
@enduml
