"起票者" as user -> "BlackPoker運営" as BP : issue起票


alt 修正がない場合（質問回答など）

user <- BP : 返信

else 修正がある場合

user <- BP : 対応開始連絡
note bottom
確認事項がある場合
質問させて頂きます
end note

user <- BP : 対応完了連絡

end

BP -> BP : issueクローズ
note bottom
更に質問・要望等がある場合
再度issueを作成して下さい
end note
