import { act, renderHook } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import scenario from "../src/data/tutorials/entry16.json";
import { RESULT_MS, useSceneInteraction } from "../src/hooks/useSceneInteraction";
import type { TutorialScene, TutorialStep } from "../src/types";
import type { InteractionInput } from "../src/lib/interaction.mjs";
afterEach(() => { vi.useRealTimers(); });
it("兵士召喚は操作なしで進まず、3つの正解操作後だけ完了する", () => {
  vi.useFakeTimers();
  const scene = { ...scenario.scenes[2], presentation: "interactive" } as TutorialScene;
  const steps = scene.stepIds.map((id) => scenario.steps.find((s) => s.id === id)) as TutorialStep[];
  const { result } = renderHook(() => useSceneInteraction(scene, steps));
  const input = (value: InteractionInput) => act(() => result.current.attempt(value));
  const wait = () => act(() => vi.advanceTimersByTime(RESULT_MS));
  act(() => vi.advanceTimersByTime(10000));
  expect(result.current.microIndex).toBe(0);
  input({ kind: "card", card: { player: "B", zone: "bulwarks", card: "D5" } });
  expect(result.current.board).toEqual(steps[0].board.before);
  input({ kind: "card", card: { player: "A", zone: "bulwarks", card: "D5" } });
  expect(result.current.board?.A.bulwarks[0].state).toBe("drive");
  wait();
  expect(result.current.prompt).toContain("ライフの一番上");
  expect(result.current.prompt).not.toContain("♠3");
  input({ kind: "card", card: { player: "A", zone: "life", card: "S3" } });
  input({ kind: "zone", player: "B", zone: "grave" });
  expect(result.current.board).toEqual(steps[1].board.before);
  input({ kind: "zone", player: "A", zone: "grave" });
  wait();
  expect(result.current.complete).toBe(false);
  input({ kind: "drop", source: { player: "A", zone: "hand", card: "S2" }, player: "A", zone: "soldiers" });
  expect(result.current.board).toEqual(steps[2].board.after);
  wait();
  expect(result.current.complete).toBe(true);
  act(() => result.current.replay());
  expect(result.current.board).toEqual(steps[0].board.before);
});
