
rectangle ルール指針

frame ルール{
rectangle コアルール as core
rectangle 共通ルール as common
rectangle フォーマット as format
rectangle 対戦レギュレーション as match_reg
rectangle フレーム as frame
rectangle オプション as options
' rectangle プレイヤー as player

core <|-- common : 継承

common <|-- format : 継承

match_reg o-- format : 内包
match_reg o-- frame : 内包
match_reg o-- options : 内包

' match_reg <. player : 選択

format <.. options : 依存
format <. frame : 依存
frame <.. options : 依存

}

ルール指針 --> ルール : 具体化

note right of match_reg #white
プレイヤーは対戦する前に
対戦レギュレーションを選択する
end note
