
hide members
hide circle

abstract class コアルール
abstract class 共通ルール

package フォーマット {
    class 拡張フォーマット
    class 通常フォーマット
}

class 対戦レギュレーション 

note right of 対戦レギュレーション
    対戦する際に決める規則
end note

対戦レギュレーション ..> フォーマット : 参照
共通ルール ..|> コアルール : 具体化
フォーマット ..> 共通ルール : 参照
通常フォーマット ^- 拡張フォーマット : 拡張



note right of コアルール : ターン制ゲームに適応できる抽象的なルール定義
note right of 共通ルール : コアルールを具体化したルール定義
note right of 通常フォーマット
ライト、スタンダードなどの
具体的なフォーマット定義
end note
note right of 拡張フォーマット
エクストラなどの通常フォーマットを
拡張したフォーマット定義


end note

