rectangle コアルール as core
rectangle 共通ルール as common

frame フォーマット as format{
    rectangle アクションリスト
    rectangle エクストラリスト
}

rectangle 対戦レギュレーション as regulation

core <- common : 参照
common <-- format : 参照
format <- regulation : 参照
