# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'BlackPoker'
copyright = '2013 BlackPoker'
author = 'もりくま'
numfig = True
numfig_format = {
    'figure': 'Fig. %s',
    'table': 'Table %s',
    'code-block': 'Listing %s',
    'section': '{number} {name}'
}
release = '2026/03/31'
version = '第9.0版'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinxcontrib.plantuml', 'sphinx.ext.mathjax', 'sphinx.ext.todo', 'sphinx.ext.githubpages']

plantuml = 'plantuml'
plantuml_output_format = 'svg_img'
plantuml_latex_output_format = 'pdf'


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.

# import sphinx_rtd_theme


[extensions]
todo_include_todos = True

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
# html_theme = "sphinx_rtd_theme"
html_title = 'BlackPoker'
html_theme = 'insipid'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_logo = '_static/blackpoker.svg'

html_theme_options = {
    # ----------
    # insipid
    # ----------
    'body_centered': False,
    'breadcrumbs': True,
    'body_max_width' : None

    # ----------
    # redoc
    # ----------
    # # 'canonical_url': '',
    # 'analytics_id': 'UA-66362035-2',  #  Provided by Google in your dashboard
    # 'logo_only': False,
    # 'display_version': True,
    # # 'prev_next_buttons_location': 'bottom',
    # # 'style_external_links': False,
    # # 'vcs_pageview_mode': '',
    # 'style_nav_header_background': 'black',
    # # Toc options
    # # 'collapse_navigation': True,
    # # 'sticky_navigation': True,
    # # 'navigation_depth': 4,
    # # 'includehidden': True,
    # # 'titles_only': False
}

# replace "view page source" with "edit on github" in Read The Docs theme
#  * https://github.com/readthedocs/sphinx_rtd_theme/issues/529
html_context = {
  'display_github': True,
  'github_user': 'BlackPoker',
  'github_repo': 'BlackPoker',
  'github_version': 'master/source/',
}

html_show_sourcelink = True
html_search_language = 'ja'
html_favicon = '_static/favicon.ico'

# -- Options for HTML output -------------------------------------------------

# LaTeX の docclass 設定
latex_docclass = {'manual': 'jsbook'}

# PDF ロゴをビルド時に取り込む設定
latex_additional_files = [
    '_static/blackpoker_logo.pdf',  # 実際のファイル名に合わせる
]

latex_elements = {
    'maketitle': r'''
\begin{titlepage}
\begin{center}
\vspace*{25mm}

%% ロゴを PDF で中央配置
\includegraphics[width=4cm]{blackpoker_logo.pdf}  %% ファイルパスは latex_additional_files に合わせる

\vspace{20mm}
{\Huge \textbf{BlackPoker 公式ルール}}\\[10mm]
{\Large トランプだけでトレーディングカードゲームみたいに遊ぶ方法}\\[30mm]

%% バージョン・リリース情報を埋め込む
{\huge %(version)s}\\[20mm]

{\Large %(author)s 著} \\[5mm]
{\Large %(release)s 発行}\\[10mm]

{\small © %(copyright)s}

\end{center}
\end{titlepage}

%% 表紙の次に空白ページを挟む
\clearpage
\thispagestyle{empty}  %% ページ番号などを非表示にする
\phantomsection
\null                  %% 何もないページを出力
\clearpage             %% さらに改ページして本文へ
''' % {
    'project': project,
    'version': version,
    'author': author,
    'release': release,
    'copyright': copyright,
},
    'preamble': r'''
\makeindex
\makeatletter
%% 「\spxentry キーワード … ページ」をそのまま「\item キーワード … ページ」に置き換える
\renewcommand{\spxentry}{\item}
\renewcommand\sphinxlineitem[2]{%
  %% safe test of whether #2 is \sphinxlineitem
  \sphinx@gobto@sphinxlineitem#2\@gobbletwo\sphinxlineitem\unless
  \iftrue
    %% Accumulate successive terms until actual definition or sub-list is found
    \spx@lineitemlabel\expandafter{\the\spx@lineitemlabel\strut#1\\}%
  \else
    %% Issue the \item command with possibly multi-line contents
    \item[\kern\labelwidth\kern-\itemindent\kern-\leftmargin
          {\parbox[t]{1.4\linewidth}{%% <- ここで幅を調整
          \raggedright
          \the\spx@lineitemlabel%% Accumulated terms before this one, CR separated
          \strut#1}}%% No \par token allowed here, but the \parbox will insert one tacitly at end
          \kern-\labelsep]%
    \spx@lineitemlabel{}%
    %% This causes the label to be typeset (filling up the line), clearing up
    %% things in case a nested list follows.
    \leavevmode
  \fi #2%
}
\makeatother
''',
    'printindex': r'\printindex',
}

