name: release build3

# vから始まるタグが付いたら実行する（例: v1, v1.2, v1.2.3）
on:
  push:
    tags: ['v*']

jobs:
  release:
    name: release build
    runs-on: ubuntu-latest
    steps:
      # 準備
      - name: checkout
        uses: actions/checkout@v2
      - name: pull builder image
        run: docker pull macrat/sphinx-pdf

      # ビルドする
      - name: build
        run: docker run --rm --user $UID -v `pwd`:/docs macrat/sphinx-pdf

      # HTMLはzipにまとめる
      - name: create zip
        run: |
          mv ./_build/html ./manual
          zip -r HTML.zip ./manual

      # GitHubにリリースを作る
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      # PDFファイルをリリースページにアップロード
      - name: upload PDF
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./_build/latex/sphinx.pdf
          asset_name: manual_PDF.pdf
          asset_content_type: application/pdf

      # HTMLを固めたzipをリリースページにアップロード
      - name: upload HTML
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./HTML.zip
          asset_name: manual_HTML.zip
          asset_content_type: application/zip